FORMS-9473: replaced parsys with container with responsive grid
adobe/aem-project-archetype pull request #1121
Opened 2023-08-17 10:36 UTC by egmox

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-22 05:23 UTC, barshat7 commented on src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/template-types/af-page-v2/policies/.content.xml
> +            jcr:title="Header"
do we really need title and layout in policies?

2023-08-22 05:27 UTC, barshat7 commented on src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/basic-af/initial/.content.xml
> +                sling:resourceType="wcm/foundation/components/responsivegrid"
I might be missing something here, but what is the change done here? The resourceType still seems to be the same. Only the tag name is changed rom parsys1 to container1, does this even make any difference? I believe its just a name

2023-09-06 09:18 UTC, barshat7 approved these changes

2023-09-06 10:01 UTC, pankaj-parashar requested changes
Container component should be replaced only for core component AF related artifacts.

- Blank AF v2 template
- AF Page V2 template type

Basic and Blank templates (Foundation AF component) shouldn't be changed.
cc : @sakshi-arora1

2023-09-06 11:00 UTC, pankaj-parashar approved these changes

2023-09-06 15:28 UTC, merged