CIF-1608 - Category Carousel Component
adobe/aem-project-archetype pull request #524
Opened 2020-10-06 10:16 UTC by LSantha

* added new carousel clientlib for CIF

## Related Issue

CIF-1608

## How Has This Been Tested?

Manually.

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2020-10-06 13:51 UTC, dplaton approved these changes

2020-10-07 07:58 UTC, herzog31 requested changes
Where are the proxy component and the policies for the new `categorycarousel` component? The changes should be similar to https://github.com/adobe/aem-cif-guides-venia/pull/72.

2020-10-15 08:31 UTC, LSantha commented
I've added the component policy and proxy.

2020-10-15 08:48 UTC, herzog31 approved these changes

2020-10-26 10:27 UTC, alkim91 approved these changes

2020-10-26 10:28 UTC, merged