Issue/849 vulnerable third party
adobe/aem-project-archetype pull request #851
Opened 2021-12-16 08:52 UTC by bpauli

This PR is a partial fix for the vulnerabilities issue reported in #849 . It fixes the issues for the ui.frontend.general and ui.tests module.

2021-12-16 12:36 UTC, vladbailescu commented on src/main/archetype/pom.xml
> +                        <nodeVersion>v12.22.7</nodeVersion>
Current LTS is 16, shouldn't we bump to it already?

2021-12-16 12:37 UTC, vladbailescu approved these changes

2021-12-17 08:19 UTC, bartoszglow requested changes
`npm audit` on node `16.13.1` and npm `8.1.2` produces `7 moderate severity vulnerabilities`.

2021-12-17 08:19 UTC, bartoszglow commented on src/main/archetype/ui.frontend.general/webpack.common.js
> +            ]})
please push `})` to the next line

2021-12-17 08:19 UTC, bartoszglow commented on src/main/archetype/ui.frontend.general/package.json
>      "css-loader": "^3.0.0",
it would be great to upgrade `css-loader` package to latest version.

2021-12-17 08:19 UTC, bartoszglow commented on src/main/archetype/ui.frontend.general/webpack.dev.js
> +const {merge} = require('webpack-merge');
make some space for merge in brackets :)

2021-12-17 08:19 UTC, bartoszglow commented on src/main/archetype/ui.tests/test-module/lib/commons.js
> +const format = require('date-fns').format;
what was the reason to replace `moment` with `format`? Is `moment` somehow vulnerable?

2021-12-17 14:28 UTC, bpauli commented on src/main/archetype/pom.xml
> +                        <npmVersion>8.3.0</npmVersion>
I had to switch back to node 12 as there is a dependency issue within the ui.frontend.react module

2021-12-17 16:20 UTC, bartoszglow approved these changes

2021-12-20 10:10 UTC, merged