Cq 4343453
adobe/aem-project-archetype pull request #943
Opened 2022-06-14 13:51 UTC by barshat7

Do Not Merge

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-14 14:01 UTC, barshat7 commented on src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/policies/.content.xml
> +                  jcr:description="Policy of the Adaptive Form V2 Container"
@rismehta  I am a little doubtful here. I have created a new policy that has component group 'apptitle - Adaptive Forms', as of now only formcontainer is part of this group. 
I have used this policy in v2 template and template type.

2022-06-15 09:27 UTC, rismehta commented on src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/adaptiveForm/formpage/.content.xml
> +    jcr:title="Adaptive Form Enablement - Page Component"
Adaptive Form Page component

2022-06-15 09:35 UTC, rismehta requested changes

2022-06-15 09:35 UTC, rismehta commented on src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/adaptiveForm/formpage/.content.xml
> +    jcr:description="Adaptive Form Enablement - Page Component"
Remove the description

2022-06-15 09:35 UTC, rismehta commented on src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/template-types/af-page-v2/initial/.content.xml
> +        sling:resourceType="fd/af/components/page2/aftemplatedpage"
${appId}/components/page

2022-06-15 09:35 UTC, rismehta commented on src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/template-types/af-page-v2/structure/.content.xml
> +            actionType="fd/fp/components/actions/portalsubmit"
Delete all this

2022-06-15 09:35 UTC, rismehta commented on src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/template-types/af-page-v2/structure/.content.xml
> +        sling:resourceType="fd/af/components/page2/aftemplatedpage">
Change the resource type as mentioned above

2022-06-15 09:35 UTC, rismehta commented on src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/blank-af-v2/initial/.content.xml
> +            actionType="fd/fp/components/actions/portalsubmit"
Delete all these properties

2022-06-15 09:35 UTC, rismehta commented on src/main/archetype/ui.frontend.react.forms.af/README.md
> +This application is built to consume the AEM model of a site. It will automatically generate the layout using the helper components from the [`@adobe/aem-react-editable-components`](https://www.npmjs
This application is built to consume the form model definition of an adaptive form

2026-02-19 15:52 UTC, closed without merging